development:
  clients:
    default:
      database: quiz_app_development
      hosts:
        - localhost:27017
      options:
  options:
development:
  clients:
    default:
      database: quiz_app
      hosts:
        - localhost:27017
      options:
  options:
